jdbc.driverClassName=org.postgresql.Driver
jdbc.url=jdbc:postgresql://155.212.166.137:22/later
jdbc.username=dbuser
jdbc.password=12345

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.sql.init.mode=always